### ISSUE TITLE
2.0 Roadmap

### ISSUE THREAD

**Issue by gakimball** [zurb/octophant#6]
- [ ] CLI Interface
- [ ] Configure paths/groups with a config file
- [ ] Combine variables from multiple sources into one file
- [ ] Migration guide between versions of packages
